application: 23isprime
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /lib
  static_dir: lib

- url: /images
  static_dir: images




- url: /.*
  script: helloworld.app







