application: weathercwxstat
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico


- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /.*
  script: index.py


